#!/bin/bash

# Constants
RESET='\033[0m'
RED='\033[38;5;1m'
GREEN='\033[38;5;2m'
YELLOW='\033[38;5;3m'
MAGENTA='\033[38;5;5m'
CYAN='\033[38;5;6m'
BOLD='\033[1m'

# Functions

stderr_print() {
    local bool="${QUIET:-false}"
    # comparison is performed without regard to the case of alphabetic characters
    shopt -s nocasematch
    if ! [[ "$bool" = 1 || "$bool" =~ ^(yes|true)$ ]]; then
        printf "%b\\n" "${*}" >&2
    fi
}

log() {
    stderr_print "${CYAN}nagios ${MAGENTA}$(date "+%T.%2N ")${RESET}${*}"
}

info() {
    log "${GREEN}INFO ${RESET} ${*}"
}

warn() {
    log "${YELLOW}WARN ${RESET} ${*}"
}

error() {
    log "${RED}ERROR${RESET} ${*}"
}

print_welcome_page() {
    if [[ -z "${DISABLE_WELCOME_MESSAGE:-}" ]]; then
        local github_url="https://github.com/arajczy/nagios"

        log ""
        log "${BOLD}Welcome to the Nagios Core container${RESET}"
        log "Subscribe to project updates by watching ${BOLD}${github_url}${RESET}"
        log "Submit issues and feature requests at ${BOLD}${github_url}/issues${RESET}"
        log ""
    fi
}
