#!/command/with-contenv bash

# Constants
RESET='\033[0m'
RED='\033[38;5;1m'
GREEN='\033[38;5;2m'
YELLOW='\033[38;5;3m'
MAGENTA='\033[38;5;5m'
CYAN='\033[38;5;6m'
BOLD='\033[1m'

# Functions

stderr_print() {
  local bool="${QUIET:-false}"
  # comparison is performed without regard to the case of alphabetic characters
  shopt -s nocasematch
  if ! [[ "$bool" = 1 || "$bool" =~ ^(yes|true)$ ]]; then
    printf '%b\n' "$@" >&2
  fi
}

log() {
  set -- "${@/#/${CYAN}nagios ${MAGENTA}$(date "+%T.%2N") ${RESET}}"
  stderr_print "$@"
}

info() {
  set	-- "${@/#/${GREEN}INFO ${RESET}}"
  log "$@"
}

warn() {
  set -- "${@/#/${YELLOW}WARN ${RESET}}"
  log "$@"
}

error() {
  set -- "${@/#/${RED}ERROR ${RESET}}"
  log "$@"
}

print_welcome_page() {
  if [[ -z "${DISABLE_WELCOME_MESSAGE:-}" ]]; then
    local github_url="https://github.com/arajczy/docker-nagios"

    log \
      "" \
      "${BOLD}Welcome to the Nagios Core container${RESET}" \
      "Subscribe to project updates by watching ${BOLD}${github_url}${RESET}" \
      "Submit issues and feature requests at ${BOLD}${github_url}/issues${RESET}" \
      ""
  fi
}
