#!/command/with-contenv bash

. /etc/s6-overlay/lib/logger

info "Setting Mail Host to ${HOSTNAME}, Mail Name to ${NAGIOS_FQDN}"
echo ${NAGIOS_FQDN} > /etc/mailname
postconf \
  myhostname=${HOSTNAME} \
  mydestination="\&myhostname, ${NAGIOS_FQDN}, localhost.hu, localhost"

if [ ! -z ${MAIL_RELAY_HOST} ]; then
  info "Setting Mail Relay Host to ${MAIL_RELAY_HOST}"
  postconf relayhost=${MAIL_RELAY_HOST}

  if [ ! -z ${MAIL_ADDRESS} ] && [ ! -z ${MAIL_PASS} ]; then
    info "Setting mail relay authentication"
    echo "${MAIL_RELAY_HOST} ${MAIL_ADDRESS}:${MAIL_PASS}" > /etc/postfix/password_map
    postmap /etc/postfix/password_map
    chmod 400 /etc/postfix/password_map.db
    rm /etc/postfix/password_map
  fi
fi

#postfix runs in a chroot and needs resolv.conf to resolve hostnames
cp /etc/resolv.conf /var/spool/postfix/etc/resolv.conf
