name: Build and Publish

on:
  push:
    branches:
      - trunk
    tags:
      - v*.*.*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/nagios

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign 
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.2.0
        with:
          cosign-release: 'v2.1.1'

      # https://github.com/docker/setup-buildx-action
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # https://github.com/docker/login-action
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata for Fedora
        id: fedora-meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            fedora
            latest
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=semver,suffix=fedora,pattern={{major}}
            type=semver,suffix=fedora,pattern={{major}}.{{minor}}
            type=semver,suffix=fedora,pattern={{version}}

      - name: Extract metadata for Ubuntu
        id: ubuntu-meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ubuntu
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=semver,suffix=ubuntu,pattern={{major}}
            type=semver,suffix=ubuntu,pattern={{major}}.{{minor}}
            type=semver,suffix=ubuntu,pattern={{version}}

      # https://github.com/docker/build-push-action
      - name: Build and push image fedora
        id: fedora-build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./fedora
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.fedora-meta.outputs.tags }}
          labels: |
            ${{ steps.fedora-meta.outputs.labels }}
            org.opencontainers.image.author=Adam Rajczy
            org.opencontainers.image.description=Nagios Core
            org.opencontainers.image.title=nagios
            org.opencontainers.image.version=4.5.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push image ubuntu
        id: ubuntu-build-and-push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./ubuntu
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.ubuntu-meta.outputs.tags }}
          labels: |
            ${{ steps.fedora-meta.outputs.labels }}
            org.opencontainers.image.author=Adam Rajczy
            org.opencontainers.image.description=Nagios Core
            org.opencontainers.image.title=nagios
            org.opencontainers.image.version=4.5.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # https://github.com/sigstore/cosign
      - name: Sign the published image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.fedora-meta.outputs.tags }}
          DIGEST: ${{ steps.fedora-build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.ubuntu-meta.outputs.tags }}
          DIGEST: ${{ steps.ubuntu-build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
